version: '3.9'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app # (dockerエンジン内？の)ローカルをコンテナ内にマウント
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true 